export const TASKS_BOARD_DATA = {
	Todo: [
		{
			id: 'todo1',
			status: 'Todo',
			task: 'This is todo Task 1',
			assignee: 'me',
			days: 5,
			hours: 12,
			priority: 'high',
		},
		{
			id: 'todo2',
			status: 'Todo',
			task: 'This is todo Task 2',
			assignee: 'me',
			days: 5,
			hours: 12,
			priority: 'high',
		},
		{
			id: 'todo3',
			status: 'Todo',
			task: 'This is todo Task 3',
			assignee: 'me',
			days: 5,
			hours: 12,
			priority: 'high',
		},
		{
			id: 'todo4',
			status: 'Todo',
			task: 'This is todo Task 4',
			assignee: 'me',
			days: 5,
			hours: 12,
			priority: 'high',
		},
	],

	'In-Progress': [
		{
			id: 'todo5',
			status: 'In-Progress',
			task: 'This is in-progess Task 1',
			assignee: 'me',
			days: 5,
			hours: 12,
			priority: 'high',
		},
		{
			id: 'todo6',
			status: 'In-Progress',
			task: 'This is in-progess Task 2',
			assignee: 'Nimesh',
			days: 5,
			hours: 12,
			priority: 'high',
		},
		{
			id: 'todo7',
			status: 'In-Progress',
			task: 'This is in-progess Task 3',
			assignee: 'me',
			days: 5,
			hours: 12,
			priority: 'high',
		},
	],

	Completed: [
		{
			id: 'todo8',
			status: 'Completed',
			task: 'This is completed Task 1',
			assignee: 'me',
			days: 5,
			hours: 12,
			priority: 'high',
		},
		{
			id: 'todo9',
			status: 'Completed',
			task: 'This is completed Task 2',
			assignee: 'me',
			days: 5,
			hours: 12,
			priority: 'high',
		},
		{
			id: 'todo10',
			status: 'Completed',
			task: 'This is completed Task 3',
			assignee: 'me',
			days: 5,
			hours: 12,
			priority: 'high',
		},
		{
			id: 'todo11',
			status: 'Completed',
			task: 'This is completed Task 4',
			assignee: 'me',
			days: 5,
			hours: 12,
			priority: 'high',
		},
	],
};
